config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations'
  }
  root 'dashboard#home'
  get '/books' => 'books#index'
  get '/users' => 'users#index'
  patch '/users/:id' => 'users#update', as: 'update_user'
  get '/books/new' => 'books#new'
  post 'books' => 'books#create'
  get '/category/new' => 'category#new'
  get '/categories' => 'category#index'
  post 'categories' => 'category#create'
  get 'categories/:id' => 'category#show', as: 'category'
  get 'users/:id' => 'users#show', as: 'user_show'
  get '/users/:id/edit' => 'users#edit', as: 'edit_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def log_response(object)
    Rails.logger.debug { '#' * 50 }
    Rails.logger.debug { object.inspect }
    Rails.logger.debug { '#' * 50 }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout 'dashboard'
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    log_response @book.errors.full_messages
    redirect_to books_path
  end

  def index
    @books = Book.all
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :image, :user_id, :category_id)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  layout 'dashboard'
  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @books = @category.books
  end

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new category_params
    @category.save
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def home
    log_response current_user
    @books = Book.all
    @users = User.all
    @categories = Category.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::SessionsController
  skip_before_action :authenticate_user!
  protect_from_forgery prepend: true
  layout 'session'
  def create
    log_response registration_params
    @user = User.new(registration_params)
    @user.save
    redirect_to root_path
    log_response @user.errors.full_messages
  end

  private

  def registration_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :username)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protect_from_forgery prepend: true
  layout 'session'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'dashboard'
  skip_before_action :authenticate_user!
  before_action :set_user, only: [:edit, :show, :update]

  def index
    @users = User.all
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to root_path
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :location, :website, :twitter_username, :bio, :image, :tagline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<section class="content">
  <h2>Books</h2>
  <br>
  <% unless @books.empty? %>
  <div class="box-body no-padding">
    <table class="table">
      <tbody>
        <tr>
          <th>S.No</th>
          <th>Cover</th>
          <th>Title</th>
          <th>Author</th>
          <th>
            Category
          </th>
          <th>Added by</th>
        </tr>
        <% @books.each_with_index do |book, index| %>
        <tr>
          <td>
            <%= index+1 %>
          </td>
          <% if book.image.present? %>
          <td><%= image_tag book.image.url, width: '75px', height: '100px' %></td>
        <% else %>
          <td>None</td>
          <% end %>
          <td><%= book.title %></td>
          <td>
            <%= book.author %>
          </td>
          <td><%= link_to book.category.name, category_path(book.category.id), method: :get %></td>
          <td>
            <%= link_to book.user.username, user_show_path(book.user.id), method: :get %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p class="warning">No records!</p>
  <% end %>
</section>

app/views/books/new.html.erb
<section class="content">
  <h2>Add a Book</h2>
  <div class="row">
    <div class="col-md-5">
      <%= bootstrap_form_for @book do |f| %>
      <div class="row">
        <div class="col-md-6">
          <%= f.text_field :title, autofocus: true, required: true %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :author, label: 'Author' %>
        </div>
        <div class="col-md-6">
          <%= f.collection_select :category_id, Category.order(:name),:id,:name, required: true, include_blank: 'None' %>
        </div>
        <div class="col-md-6">
          <%= f.file_field :image, label: 'Cover', class: 'btn btn-default' %>
        </div>
        <div class="col-md-6">
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit 'Add Book', class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/category/index.html.erb
<section class="content">
  <h2>Categories</h2>
  <br>
  <% unless @categories.empty? %>
  <div class="box-body no-padding">
    <table class="table">
      <tbody>
        <tr>
          <th>S.No</th>
          <th>Name</th>
          <th>Total Books</th>
        </tr>
        <% @categories.each_with_index do |category, index| %>
        <tr>
          <td>
            <%= index+1 %>
          </td>
          <td><%= link_to category.name, category_path(category.id), method: :get %></td>
          <td>
            <%= category.books.count %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p class="warning">No records!</p>
  <% end %>
</section>

app/views/category/new.html.erb
<section class="content">
  <h2>Add a Category</h2>
  <div class="row">
    <div class="col-md-5">
      <%= bootstrap_form_for @category do |f| %>
      <div class="row">
        <div class="col-md-6">
          <%= f.text_field :name, autofocus: true, required: true %>
        </div>
        <div class="col-md-6">
          <%= f.text_area :description, label: 'Description' %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit 'Add Category', class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/category/show.html.erb
<section class="content">
  <h2><%= @category.name %></h2>
  <p><%= @category.description %></p>
  <br>
  <% unless @books.empty? %>
  <div class="box-body no-padding">
    <table class="table">
      <tbody>
        <tr>
          <th>S.No</th>
          <th>Cover</th>
          <th>Title</th>
          <th>Author</th>
          <th>Added by</th>
        </tr>
        <% @books.each_with_index do |book, index| %>
        <tr>
          <td>
            <%= index+1 %>
          </td>
          <% if book.image.present? %>
          <td><%= image_tag book.image.url, width: '75px', height: '100px' %></td>
          <% else %>
          <td>None</td>
          <% end %>
          <td>
            <%= book.title %>
          </td>
          <td>
            <%= book.author %>
          </td>
          <td><%= link_to book.user.username, user_show_path(book.user.id), method: :get %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p class="warning">No records!</p>
  <% end %>
</section>

app/views/dashboard/home.html.erb
<section class="content">
  <br>
  <div class="row">
    <% %w(Users Books).each do |item| %>
    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-<%= item == "Users" ? "red" : "green" %>">
        <div class="inner">
          <h3><%= item == "Users" ? @users.count : @books.count %></h3>
          <p class="text-capitalize"><%= item %></p>
        </div>
        <div class="icon">
          <i class="fa fa-<%= item == 'Users' ? "users" : "book" %>"></i>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <br>
  <%= link_to(books_new_path, method: :get, class: "btn btn-primary") do%>
    <i class="fa fa-plus-circle text-white" aria-hidden="true"></i>&nbsp; New Book
  <% end %>
  &nbsp;
  <%= link_to(category_new_path, method: :get, class: "btn btn-primary") do%>
    <i class="fa fa-plus-circle text-white" aria-hidden="true"></i>&nbsp; New Category
  <% end %>
</section>

app/views/layouts/_aside.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="treeview">
        <a href="#">
          <i class="fa fa-book"></i>
          <span>Books</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-right pull-left"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to(books_new_path, method: :get) do%>
            <i class="fa fa-plus text-green"></i>
            Add Book
            <% end %>
          </li>
          <li>
            <%= link_to(books_path, method: :get) do%>
            <i class="fa fa-circle-o text-blue"></i>
            All Books
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-users"></i>
          <span>Users</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-right pull-left"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to(users_path, method: :get) do%>
            <i class="fa fa-circle-o text-yellow"></i>
            All Users
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-list"></i>
          <span>Category</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-right pull-left"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to(categories_path, method: :get) do%>
            <i class="fa fa-circle-o text-green"></i>
            All Categories
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </section>
</aside>

app/views/layouts/_header.html.erb
<header class="main-header">
  <%= link_to root_path, class: "logo", method: :get do %>
  <span class="logo-mini">
    <b>BS</b>
  </span>
  <span class="logo-lg">
    <b>Book Shelf</b>
  </span>
  <% end %>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <span class="hidden-xs">
              <% if current_user.image.present? %>
              <%= image_tag current_user.image.url, class: "img-circle", width: '25px', height: '25px' %>
              <% else %>
              <i class="fa fa-user" aria-hidden="true"></i>
              <% end %>
              &nbsp;<%= current_user.name %>
            </span>
          </a>
          <ul class="dropdown-menu user-dropdown">
            <li>
              <%= link_to 'My Profile', user_show_path(current_user.id), method: :get %>
            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to 'Home', root_path %></h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Shelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'adminlte', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <%= render 'layouts/aside' %>

      <div class="content-wrapper">
        <%= yield %>
      </div>
      <!-- Content Wrapper. Contains page content -->

      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b>
          1.0.0
        </div>
        <center>
          <strong>Made with
            &nbsp; <i class="fa fa-heart" aria-hidden="true"></i>
            &nbsp; under &nbsp;<a href="https://creativecommons.org/">Creative Commmons License</a> &nbsp;
            <i class="fa fa-creative-commons" aria-hidden="true"></i>
            &nbsp;</strong>
        </center>
      </footer>

      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div>
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Shelf</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'adminlte', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/users/edit.html.erb
<section class="content">
  <h2>Edit Profile</h2>
  <div class="row">
    <div class="col-md-5">
      <%= bootstrap_form_for @user, url: update_user_path(@user) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <%= f.text_field :name, autofocus: true, required: true %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :location %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :tagline, label: 'Tagline' %>
        </div>
        <div class="col-md-6">
          <%= f.text_area :bio, label: 'Bio' %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :website, label: 'Website' %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :twitter_username, label: 'Twitter Username' %>
        </div>
        <div class="col-md-6">
          <%= f.file_field :image, label: 'Profile Picture', class: 'btn btn-default' %>
        </div>
      </div>
      <div class="actions">
        <%= f.submit 'Update User', class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="content">
  <h2>Users</h2>
  <br>
  <% unless @users.empty? %>
  <div class="box-body no-padding">
    <table class="table">
      <tbody>
        <tr>
          <th>S.No</th>
          <th>Name</th>
          <th>Email</th>
          <th>Total Books</th>
        </tr>
        <% @users.each_with_index do |user, index| %>
        <tr>
          <td>
            <%= index+1 %>
          </td>
          <td><%= user.name %></td>
          <td>
            <%= user.email %>
          </td>
          <td>
            <%= user.books.count %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p class="warning">No records!</p>
  <% end %>
</section>

app/views/users/show.html.erb
<section class="content">
  <div class="row">
    <div class="col-md-4">
      <div class="box box-widget widget-user-2">
        <div class="widget-user-header bg-blue">
          <div class="widget-user-image">
            <%= image_tag @user.image.url, class: "img-circle" if @user.image.present? %>
          </div>
          <h3 class="widget-user-username"><%= @user.name %></h3>
          <h5 class="widget-user-desc"><%= @user.tagline %></h5>
        </div>
        <div class="box-footer">
          <div class="row">
            <div class="col-sm-4 border-right">
              <div class="description-block">
                <h5 class="description-header"><%= @user.books.count %></h5>
                <span class="description-text">BOOKS</span>
              </div>
            </div>
            <% if @user == current_user %>
            <div class="description-block">
              <%= link_to(edit_user_path(@user), method: :get, class: "btn btn-default") do%>
              <i class="fa fa-pencil text-white" aria-hidden="true"></i>&nbsp; Edit Profile
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="box box-primary">
        <div class="box-header with-border">
          <% if @user == current_user %>
          <h3 class="box-title">About Me (<%= @user.username %>)</h3>
        <% else %>
          <h3 class="box-title">About
            <%= @user.name %>
            (<%= @user.username %>)</h3>
          <% end %>
        </div>
        <div class="box-body">
          <strong>
            <i class="fa fa-user margin-r-5"></i>
            Bio</strong>
          <p class="text-muted"><%= @user.bio %></p>
          <hr>
          <strong>
            <i class="fa fa-map-marker margin-r-5"></i>
            Location</strong>
          <p class="text-muted"><%= @user.location %></p>
          <hr>
          <strong>
            <i class="fa fa-link margin-r-5"></i>
            Website</strong>
          <p class="text-muted">
            <a href="<%= @user.website %>"><%= @user.website %></a>
          </p>
          <hr>
          <strong>
            <i class="fa fa-twitter margin-r-5"></i>
            Twitter</strong>
          <p class="text-muted">
            <a href="https://www.twitter.com/<%= @user.twitter_username %>"><%= @user.twitter_username %></a>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>